import { and, desc, eq, sql } from 'drizzle-orm'
import type { DbExecutor } from '../utils/db'
import { containerEvents, containers } from '../database/schema'
import type { EventSource, EventType } from '#shared/utils/domain'

export interface RecordEventInput {
  /** Client-generated UUID. Reused on retries so replays are no-ops. */
  id: string
  companyId: string
  containerId?: string | null
  eventType: EventType
  occurredAt?: Date
  actorUserId?: string | null
  actorDriverId?: string | null
  source?: EventSource
  tripId?: string | null
  locationId?: string | null
  chassisId?: string | null
  gps?: { latitude: number, longitude: number, accuracyMeters?: number } | null
  yardPosition?: Record<string, unknown> | null
  payload?: Record<string, unknown>
  notes?: string | null
  correctsEventId?: string | null
}

/** Denormalised current-state columns that an event is permitted to advance. */
export interface ContainerStatePatch {
  activePoolState?: (typeof containers.$inferInsert)['activePoolState']
  currentDriverId?: string | null
  currentLocationId?: string | null
  activeMovementId?: string | null
  currentChassisId?: string | null
  activatedAt?: Date | null
  releasedAt?: Date | null
  isLoaded?: boolean
  sealNumber?: string | null
  containerStatus?: (typeof containers.$inferInsert)['containerStatus']
}

/**
 * Append an immutable event and advance the container's denormalised state in
 * the same transaction (spec 18, 27.3).
 *
 * The caller supplies the transaction handle, so an operation that produces
 * several events (pickup → custody → chassis-attach) commits atomically.
 *
 * Idempotency: the event id is the primary key and is generated by the client,
 * so a retried offline submission conflicts and is ignored rather than creating
 * a duplicate movement (spec 33.2).
 *
 * @returns the stored event and whether this call actually inserted it
 */
export async function recordEvent(
  tx: DbExecutor,
  input: RecordEventInput,
  statePatch?: ContainerStatePatch,
): Promise<{ eventId: string, created: boolean }> {
  const occurredAt = input.occurredAt ?? new Date()

  const inserted = await tx
    .insert(containerEvents)
    .values({
      id: input.id,
      companyId: input.companyId,
      containerId: input.containerId ?? null,
      eventType: input.eventType,
      occurredAt,
      actorUserId: input.actorUserId ?? null,
      actorDriverId: input.actorDriverId ?? null,
      source: input.source ?? 'MANUAL',
      tripId: input.tripId ?? null,
      locationId: input.locationId ?? null,
      chassisId: input.chassisId ?? null,
      gpsLatitude: input.gps ? String(input.gps.latitude) : null,
      gpsLongitude: input.gps ? String(input.gps.longitude) : null,
      gpsAccuracyMeters: input.gps?.accuracyMeters ?? null,
      yardPosition: input.yardPosition ?? null,
      payload: input.payload ?? {},
      notes: input.notes ?? null,
      correctsEventId: input.correctsEventId ?? null,
    })
    .onConflictDoNothing({ target: containerEvents.id })
    .returning({ id: containerEvents.id })

  const created = inserted.length > 0

  // A replayed event must not re-apply a state transition.
  if (created && statePatch && input.containerId) {
    await tx
      .update(containers)
      .set({
        ...statePatch,
        lastActivityAt: occurredAt,
        updatedAt: new Date(),
        version: sql`${containers.version} + 1`,
      })
      .where(and(eq(containers.id, input.containerId), eq(containers.companyId, input.companyId)))
  }

  return { eventId: input.id, created }
}

/** Chronological event history for one container, newest first. */
export async function listContainerEvents(db: DbExecutor, companyId: string, containerId: string, limit = 200) {
  return db
    .select()
    .from(containerEvents)
    .where(and(eq(containerEvents.companyId, companyId), eq(containerEvents.containerId, containerId)))
    .orderBy(desc(containerEvents.occurredAt), desc(containerEvents.createdAt))
    .limit(limit)
}

/** True when this client-generated event id has already been stored. */
export async function eventExists(db: DbExecutor, companyId: string, eventId: string): Promise<boolean> {
  const rows = await db
    .select({ id: containerEvents.id })
    .from(containerEvents)
    .where(and(eq(containerEvents.id, eventId), eq(containerEvents.companyId, companyId)))
    .limit(1)
  return rows.length > 0
}
